### PR TITLE
Add code flash

### PR DESCRIPTION
**Pull request by mogimogitomato**
I added flash function When running code :)

### CODE REVIEW

**Comment by llloret** [comment]
Nice, I like it! Thank you

**Comment by ethancrawford** [comment]
@mogimogitomato - do you happen to be in contact with the creator of https://github.com/mactkg/vscode-sonic-pi at all? I just realised that you have contributed to that project previously. We had been wondering whether they were interested in merging that project with ours, since it had several useful extra features that we didn't, and we'd love to get our version to that level and into the VS Code marketplace as an 'official' Sonic Pi extension.

(I remember that this flash feature was one of the things the other project had).

**Comment by mogimogitomato** [comment]
@ethancrawford 
Yes!  I updated and ported several feature.
I read this thread and now exciting, I'll try to contact about merging.
https://in-thread.sonic-pi.net/t/vs-code-extension/3935

**Comment by ethancrawford** [comment]
Great! Thanks 😄

**Pull request merged**
